import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1761723447579 implements MigrationInterface {
    name = 'Migration1761723447579'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "reports" ("id" character varying NOT NULL, "name" character varying, "refund_start_date" date, "refund_end_date" date, "report_data" jsonb, "report_type" text NOT NULL DEFAULT 'refund', "report_status" text NOT NULL DEFAULT 'process', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "report_data_rows" ("id" character varying NOT NULL, "seq_no" integer, "refund_date" character varying, "cancel_time" character varying, "refund_type" character varying, "refund_person" character varying, "refund_charge" numeric, "refund_charge_tax" numeric, "refund_amount" numeric, "refund_trande_no" character varying, "plat_trade_no" character varying, "refund_bank_code" character varying, "refund_bank_name" character varying, "refund_account" character varying, "refund_account_name" character varying, "actual_refund_amount" numeric, "passenger_name" character varying, "encrypted_id_number" character varying, "nationality" character varying, "order_number" character varying, "ticket_no" character varying, "ticketing_station" character varying, "business_area" character varying, "office_no" character varying, "window_no" character varying, "shift_no" character varying, "operator_name" character varying, "ticketing_time" character varying, "departure_time" character varying, "train_no" character varying, "origin" character varying, "cars_number" character varying, "seat_number" character varying, "origin_code" character varying, "purchase_date" character varying, "destination" character varying, "destination_code" character varying, "arrival_time" character varying, "seat_class" character varying, "ticket_type" character varying, "original_ticket_price" character varying, "report_id" character varying, CONSTRAINT "PK_7eb02fd9b80283c9eeb1913fcb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticketing-call-logs" ("id" character varying NOT NULL, "refund_number" character varying NOT NULL, "payload" jsonb NOT NULL, "response" jsonb NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_78b4c04bad141496ea0b14c496b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refund_detail_tickets" ("id" character varying NOT NULL, "arrival_station" character varying, "cars_number" character varying, "departure_date" date, "departure_station" character varying, "identity_number" character varying, "identity_type" character varying, "name" character varying, "order_number" character varying, "purchase_price" numeric, "seat_number" character varying, "ticket_class" character varying, "ticket_number" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "refund_detail_id" character varying, CONSTRAINT "PK_300a3105c65e6a73bb2edb65c8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refund_details" ("id" character varying NOT NULL, "refund_id" character varying, "email" character varying, "phone_number" character varying, "reason" character varying, "refund_ga_number" character varying, "refund_amount" numeric, "ticket_office" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_647da5b1982b07a1411f942fcb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refunds" ("id" character varying NOT NULL, "refund_ga_number" character varying, "refund_status" character varying DEFAULT 'rbdApproval', "refund_amount" numeric, "refund_amount_data" jsonb, "refund_data" jsonb, "refund_reason" character varying, "reject_reason" character varying, "reject_by" character varying, "approval_fin_by" character varying, "approval_rbd_by" character varying, "approval_fin_at" TIMESTAMP WITH TIME ZONE, "approval_rbd_at" TIMESTAMP WITH TIME ZONE, "reject_at" TIMESTAMP WITH TIME ZONE, "refund_bank_data" jsonb, "refund_date" TIMESTAMP WITH TIME ZONE, "request_data" jsonb, "pg_callback" jsonb, "retry_attempt" jsonb, "retry_date" TIMESTAMP WITH TIME ZONE, "target_refund_date" TIMESTAMP WITH TIME ZONE, "refund_execute_data" jsonb, "notif_log" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "refund_detail_id" character varying, CONSTRAINT "PK_5106efb01eeda7e49a78b869738" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refund_logs" ("id" character varying NOT NULL, "type" character varying NOT NULL, "location" character varying NOT NULL, "detail" text NOT NULL, "msg" text NOT NULL, "notes" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d3242b85309733c792e868c0dfa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "iluma_callbacks" ("id" character varying NOT NULL, "callback_type" character varying, "request_number" character varying, "payload" jsonb, "response" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_4044e69e7b9c854ea7a9c5f9225" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "iluma_call_logs" ("id" character varying NOT NULL, "url" character varying NOT NULL, "method" text NOT NULL, "payload" jsonb, "response" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_89aa62944713ac3a1d732359627" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payment_gateways_status_enum" AS ENUM('production', 'development', 'disable')`);
        await queryRunner.query(`CREATE TABLE "payment_gateways" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pg_code" character varying NOT NULL, "pg_name" character varying NOT NULL, "credential" text NOT NULL, "credential_encrypted" text, "status" "public"."payment_gateways_status_enum" NOT NULL DEFAULT 'development', "weight" integer NOT NULL, "percentage_range" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_8b85598b98f729a67fbd9c39b00" UNIQUE ("pg_code"), CONSTRAINT "PK_2b022a3aafb792a1afe3e14e06f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b85598b98f729a67fbd9c39b0" ON "payment_gateways" ("pg_code") `);
        await queryRunner.query(`CREATE TABLE "refund_banks" ("id" character varying NOT NULL, "bank_name" character varying NOT NULL, "xendit_code" character varying, "xendit_data" jsonb, "iluma_code" character varying, "iluma_data" jsonb, "bank_status" character varying NOT NULL DEFAULT 'disable', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e1234a62c03f16b506f6654db1f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "configurations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "config_name" character varying NOT NULL, "config_value" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ef9fc29709cc5fc66610fc6a664" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bank_datas" ("id" character varying NOT NULL, "account_number" character varying NOT NULL, "account_status" character varying NOT NULL, "account_result" character varying, "iluma_data" jsonb, "last_check_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_21c55d737e433eef30f85a82167" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."api_log_debugs_signature_status_enum" AS ENUM('accepted', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "api_log_debugs" ("id" character varying NOT NULL, "endpoint" character varying NOT NULL, "payload" text NOT NULL, "signature" text NOT NULL, "signature_status" "public"."api_log_debugs_signature_status_enum" NOT NULL, "raw_payload" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6d5e736721c8688b66669b59efd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "report_data_rows" ADD CONSTRAINT "FK_11b3f2f2798db9282fb32d945d6" FOREIGN KEY ("report_id") REFERENCES "reports"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refund_detail_tickets" ADD CONSTRAINT "FK_a21a22b07192873b4d37ecb71ce" FOREIGN KEY ("refund_detail_id") REFERENCES "refund_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refunds" ADD CONSTRAINT "FK_b7468cb5e2c7cb9b34953c7ccb4" FOREIGN KEY ("refund_detail_id") REFERENCES "refund_details"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refunds" DROP CONSTRAINT "FK_b7468cb5e2c7cb9b34953c7ccb4"`);
        await queryRunner.query(`ALTER TABLE "refund_detail_tickets" DROP CONSTRAINT "FK_a21a22b07192873b4d37ecb71ce"`);
        await queryRunner.query(`ALTER TABLE "report_data_rows" DROP CONSTRAINT "FK_11b3f2f2798db9282fb32d945d6"`);
        await queryRunner.query(`DROP TABLE "api_log_debugs"`);
        await queryRunner.query(`DROP TYPE "public"."api_log_debugs_signature_status_enum"`);
        await queryRunner.query(`DROP TABLE "bank_datas"`);
        await queryRunner.query(`DROP TABLE "configurations"`);
        await queryRunner.query(`DROP TABLE "refund_banks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b85598b98f729a67fbd9c39b0"`);
        await queryRunner.query(`DROP TABLE "payment_gateways"`);
        await queryRunner.query(`DROP TYPE "public"."payment_gateways_status_enum"`);
        await queryRunner.query(`DROP TABLE "iluma_call_logs"`);
        await queryRunner.query(`DROP TABLE "iluma_callbacks"`);
        await queryRunner.query(`DROP TABLE "refund_logs"`);
        await queryRunner.query(`DROP TABLE "refunds"`);
        await queryRunner.query(`DROP TABLE "refund_details"`);
        await queryRunner.query(`DROP TABLE "refund_detail_tickets"`);
        await queryRunner.query(`DROP TABLE "ticketing-call-logs"`);
        await queryRunner.query(`DROP TABLE "report_data_rows"`);
        await queryRunner.query(`DROP TABLE "reports"`);
    }

}
